title: Zhihang Yuan's Homepage
page-top-title: Zhihang Yuan
top-section-bg-text: Management Science and Engineering
home-subtitle: Zhihang Yuan&ensp;|&ensp;袁志航
copyright-text: '&copy; Zhihang Yuan 2022-2024. All Rights Reserved.'
